### ISSUE TITLE
[Note] @JvmField

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#10]
`@JvmField`가 종종 보여서 찾아봤습니다.
요약하면 `@JvmField`는 getter/setter의 생성을 방지하는 어노테이션입니다.

## val의 경우 기본적으로 getter가 생성됨

```kotlin
    val context : Context = null
```

```java
   @NotNull
   private final Context context;

   @NotNull
   public final Context getContext() {
      return this.context;
   }
```

## @JvmField를 통해 getter 제거

```kotlin
    @JvmField
    val context : Context = null
```

```java
   @JvmField
   @NotNull
   public final Context context;
```

## var의 경우 getter/setter가 같이 생성됨

```kotlin
    var context : Context = null
```

```java
   @NotNull
   private Context context;

   @NotNull
   public final Context getContext() {
      return this.context;
   }

   public final void setContext(@NotNull Context var1) {
      Intrinsics.checkParameterIsNotNull(var1, "<set-?>");
      this.context = var1;
   }
```

## @JvmField 로 getter/setter 제거
```kotlin
    @JvmField
    var context : Context = null
```

```java
   @JvmField
   @NotNull
   public Context context;
```

따라서 @JvmField의 경우 특별히 별도의 getter/setter가 필요없이 사용하고 싶을 경우에 명시하는게 좋을 것 같습니다.

**Comment by taehwandev** [comment]
그러고보니 이건 wiki에 올라가는게 더 좋을것 같습니다!(이게 더 잘보이긴 하지만?)

**Comment by cwdoh** [comment]
코멘트를 유도하기 위해 :)

**Comment by tonyjs** [comment]
자바에서 스태틱 변수처럼 코틀린을 호출 할 때를 위해서도 `@JvmField` 가 필요하긴 해요.
`companion object` 에 value 들을 설정해줄 때를 예를들면
String이나 Int 같은 `primitive` 한 것들은 `const` 를 붙여서 접근 가능하게 만들어주는데요.
primitive 하지 않은 클래스들을 자바에서 스태틱 필드처럼 접근하고 싶은 경우에 `@JvmField` 를 붙여주면 됩니다.
```
GoodBye.kt
companion object {
    val PATTERN = Pattern.compile(...)

    @JvmField val PATTERN2 = Pattern.compile(...)
}

Hello.java
GoodBye.PATTERN // 빨간줄

GoodBye.PATTERN2 // Good
```

근데 `@JvmFiled` 를 안붙여 줘도 `GoodBye.Companion.getPattern()` 으로 접근은 가능합니다 ^^;

**Comment by cwdoh** [comment]
Slack Log: taehwan, realignist, tonyjs, cwdoh

> `const`는 프리미티브에만 쓸 수 있으니까 복잡한 타입엔 `@JvmField`를 쓰죠
> 저는 Kotlin + Vert.x + JUnit을 쓰는데, JUnit 4에서 `Rule`이 무조건 `static final` 해야해서 저 어노테이션을 썼던 것 같습니다.

> 좀 헷갈리는게 setter/getter의 유무와 const는 분명히 다른 부분이 있는 것 같은데 static final과 이어지는 연결고리를 제가 이해를 못한 것 같아서요.

> 설명을 보면 getter / setter를 만들지 않는 역할도 있지만, field로 빼놓는 역할도 있어서요.
 (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-field/index.html)
> 그 `companion object`에서 `@JvmField` 어노테이션을 추가하면 `MyClass.Companion.variable`이 아니라 `MyClass.variable`로 호출이 가능했었습니다.

> 실제로 bytecode가 어떻게 나오는지는 직접 봐야 알겠지만, 아마 필드로 빼놓는 역할 때문에 val이랑 같이 쓰면 java의 static final처럼 쓸 수 있는게 아닐까 싶습니다.

> bytecode 보면 `Companion`이 public final static 으로 잡히고 내부 const value 가 final 로 잡히네요

> ok, 일단 코틀린의 prop.과 자바의 필드 변수는 다르다부터 시작이군요.
> https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#instance-fields
> Annotating such a property with @JvmField makes it a static field with the same visibility as the property itself.
