### ISSUE TITLE
[Note] vararg 를 파라미터로 받을 때

### ISSUE THREAD

**Issue by tonyjs** [kotlin-korea/Study-Log#12]
Java 에서 `addAll(String... items)` 와 동일한 개념이 `vararg` 인데요.
`vararg` 를 인자로 받는 `fucntion` 에 `array` 를 넘겨주고 싶은 경우 `*` 을 앞에 붙여주면 되네요.
이걸 [`spread` operator](https://kotlinlang.org/docs/reference/functions.html#variable-number-of-arguments-varargs) 라고 하네요.
```
fun addAll(vararg items:String) { ... }

val list = mutableListOf<String>().apply { add("1"), ...  }

addAll(list) // 당연히 ^^ 빨간줄
addAll(list.toTypedArray()) // 빨간줄

addAll(*list.toTypedArray()) // Good!
```

**Comment by cwdoh** [comment]
spead operator가 iterator가 존재하는 경우, 이를 flatten하는 느낌 같기도 하고 궁금해서 찾아봤습니다.

기본적으로 [copy array를 호출하는 형태](https://discuss.kotlinlang.org/t/hidden-allocations-when-using-vararg-and-spread-operator/1640/3)이므로, 할당의 리스크를 줄여야 할 경우 [List 등을 쓰는 것이 추천](https://discuss.kotlinlang.org/t/allocation-of-vararge-with-spread-operator/2015/5)되는군요.

**Comment by cwdoh** [comment]
array flatten 등을 구현할 때 유용하게 사용할 수 있을 것 같습니다.
