### ISSUE TITLE
[Article] inline function

### ISSUE THREAD

**Issue by steadymoka** [kotlin-korea/Study-Log#13]
inline function 에 대해서 한번 정리해보았습니다.
[https://moka-a.github.io/android/0/](https://moka-a.github.io/android/0/)
추가 내용있으면 알려주시면 감사하겠습니다 ! ( 밑에 질문도 있어요 .. ㄷㄷ )

**Comment by cwdoh** [comment]
> 다만 컴파일러가 작업을 해줘야 하기때문에 성능에 문제가 생길 수 있다고 적혀있고, 따라서 코드가 긴함수를 넣지 말라고 적혀 있다. 여기서 약간 의문점이, 컴파일단에서 코드를 제너레이트 해서 넣는다면 런타임 성능에는 큰 문제가 없는것이 아닌가?? 라는 의문이다.

아 긴 코드에 대한 내용은 보통 인라인의 사용처는 널리 분포되는 가능성이 높고 그러한 상황에서 코드가 길다는 것이 대부분의 경우 호출의 비용보다 실행자체의 비용 비중이 높을텐데 용량-실행의 트레이드오프에 대해서 고민이 필요할 거다라는 뜻에서 달아봤습니다.

**Comment by steadymoka** [comment]
아 길고 자주 호출 되는 함수일 경우의 비용이 더 클수가 있을 수 있겠네요 !! 조금 이해가 가네요~ 감사합니다 :)

**Comment by cwdoh** [comment]
@moka-a 네, 정확히는 코드 사이즈라는 비용이 늘어나죠. :)
