### ISSUE TITLE
[SungdaySadang] 대상 소스 선정

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#2]
# 대상 소스

* 각자 원하는 소스 코드를 선택한다.
* 참여한 소스에 star를 눌러 업데이트를 구독한다.
* 다른 사람의 PR에 대해 최대한 반응(리뷰, 이모지 등)한다. :)

## 초급
- [x] https://github.com/ganadist/AndroidApiDemo
- [x] https://github.com/firebase/quickstart-android

## 중급
- [x] https://github.com/googlesamples/android-architecture/tree/dev-todo-mvvm-live
- [x] https://github.com/googlecodelabs/android-testing

## 고급
- [x] https://github.com/iammert/AndroidArchitecture

# Candidates

- [x] ~https://github.com/avjinder/Minimal-Todo~
- [x] ~https://github.com/frogermcs/InstaMaterial~
- [x] ~https://github.com/googlesamples/android-topeka/tree/master/app/src/main/java/com/google/samples/apps/topeka~
- [x] ~https://github.com/iammert/Android-MVVM-Architecture~
- [ ] ~https://github.com/afollestad/photo-affix~
- [ ] ~https://github.com/airbnb/lottie-android~
- [ ] ~https://github.com/googlesamples/android-architecture~
- [ ] ~https://github.com/androidannotations/androidannotations~
- [ ] ~https://github.com/LeeKangUk/AndroidDialer~
- [ ] ~https://github.com/sockeqwe/AdapterDelegates~
- [ ] ~https://github.com/JakeWharton/RxBinding~
- [ ] ~https://github.com/ReactiveX/RxJava~
- [ ] ~https://github.com/google/dagger~
- [ ] ~https://github.com/google/iosched~
- [ ] ~https://github.com/greenrobot/EventBus~

**Comment by ganadist** [comment]
https://github.com/ganadist/AndroidApiDemo

**Comment by Pluu** [comment]
https://github.com/jungilhan/awesome-blogs-android

**Comment by acious** [comment]
https://github.com/googlecodelabs/android-testing

**Comment by Pluu** [comment]
Android Google Sample 중 아무거나 : https://github.com/googlesamples?utf8=%E2%9C%93&q=android&type=&language=

**Comment by chonamdoo** [comment]
https://github.com/iammert/Android-MVVM-Architecture

**Comment by tonyjs** [comment]
https://github.com/googlesamples/android-topeka/tree/master/app/src/main/java/com/google/samples/apps/topeka

**Comment by Pluu** [comment]
https://github.com/frogermcs/InstaMaterial

**Comment by omjoonkim** [comment]
https://github.com/yanzhenjie/Album

**Comment by omjoonkim** [comment]
https://github.com/iammert/AndroidArchitecture

**Comment by cwdoh** [comment]
대상 소스 등은 위와 같이 선정되어 fork해두었습니다.

**Comment by heongkyun** [comment]
https://github.com/kotlin-korea/android-testing
