### ISSUE TITLE
[Kotlin] Visibility Modifiers

### ISSUE THREAD

**Issue by Pluu** [kotlin-korea/Study-Log#20]
- private means visible inside this class only (including all its members);
- protected — same as private + visible in subclasses too;
- internal — any client inside this module who sees the declaring class sees its internal members;
- public — any client who sees the declaring class sees its public members.

> [Visibility Modifiers](https://kotlinlang.org/docs/reference/visibility-modifiers.html)

**Comment by cwdoh** [comment]
[Visibility Modifiers](https://kotlinlang.org/docs/reference/visibility-modifiers.html)에서 퍼옴

```kotlin
open class Outer {
    private val a = 1
    protected open val b = 2
    internal val c = 3
    val d = 4  // public by default
    
    protected class Nested {
        public val e: Int = 5
    }
}

class Subclass : Outer() {
    // a is not visible
    // b, c and d are visible
    // Nested and e are visible

    override val b = 5   // 'b' is protected
}

class Unrelated(o: Outer) {
    // o.a, o.b are not visible
    // o.c and o.d are visible (same module)
    // Outer.Nested is not visible, and Nested::e is not visible either 
}
```
