### ISSUE TITLE
[Note] internal of `by lazy`

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#23]
의식의 흐름대로...-_-

## 값이 선언된 property

> 일단 손쉽게 보기 위해 setter가 없는 val로 보려고 했는데, `by lazy` 자체가 val 전용이다. 반대로 `lateinit`은 var 전용이고...생각해보니 당연하다. ㅜ

```kotlin
class Demo {
    val myAge : Int = 40
}
```

당연히 final과 getter를 가지는 형태로 변환된다.

```java
public final class Demo {
   private final int myAge = 40;

   public final int getMyAge() {
      return this.myAge;
   }
}
```

### 일단 `by` 키워드

`by`는 [delegate를 사용하여 prop을 정의](https://kotlinlang.org/docs/reference/delegated-properties.html)하기 위해 사용될 수 있다. 즉, 여기에서 다루는 내용은 `lazy`라는 delegate 를 통해 prop을 정의하는 것이다.

> delegate란 말그대로 위임을 뜻한다. A에 대한 b라는 delegate는 기본적으로 b가 대신 A에 접근하여 어떠한 중간 연산을 하는 등의 처리를 말한다. ObjC에서는 같은 이름의 비슷한 개념을 이용하여 각 클래스의 인터페이스를 정의하고 호출하는 방식을 사용하고는 했다.

### 다시 lazy로...

`by lazy`는 값을 사용하는 시점에 한번 람다 블록을 이용해서 initialize가 일어난다. 즉, [`lazy`라는 standard delegate](https://kotlinlang.org/docs/reference/delegated-properties.html#lazy)가 제공되고, 이것이 정의된 prop.에 lazy에 의한 delegation이 일어나는 것이다.

#### lazy 설명

대충 설명은 아래와 같다. 

> lazy()는 람다를 받고, lazy 속성을 구현하기 위한 delegate를 제공할 수 있는 Lazy<T> 인스턴스를 반환한다. 최초 get()으로의 호출이 lazy()를 통해 람다를 실행하고, 결과를 기록해두었다가, 이후의 호출에서 get() 은 단순히 기억된 값을 반환한다. + 기본적으로 **synchronized**하다는 등의 얘기가 있으니 그건 [링크 참조](https://kotlinlang.org/docs/reference/delegated-properties.html#lazy)

#### 어떻게 구현되었을까

```kotlin
class Demo {
    val myAge : Int by lazy { 40 }
}
```

```java
public final class Demo {
   @NotNull
   private final Lazy myAge$delegate;
   // $FF: synthetic field
   static final KProperty[] $$delegatedProperties = new KProperty[]{(KProperty)Reflection.property1(new PropertyReference1Impl(Reflection.getOrCreateKotlinClass(Demo.class), "myAge", "getMyAge()I"))};

   public final int getMyAge() {
      Lazy var1 = this.myAge$delegate;
      KProperty var3 = $$delegatedProperties[0];
      return ((Number)var1.getValue()).intValue();
   }

   public Demo() {
      this.myAge$delegate = LazyKt.lazy((Function0)null.INSTANCE);
   }
}
```

* 클래스내에 $delegate를 붙인 `private final Lazy myAge$delegate;`가 선언된다.
* 생성자에서 이에 대해 `LazyKt.lazy`를 assign한다.
> 궁금증. Lazy.lazy는 무엇을 하는가???? 당연히도 주어진 초기화 블록을 실행하는 역할을 하겠지

* getter에서
    * Lazy로 선언된 `myAge$delegate`를 가져온다.
    * 정적으로 선언된 `$$delegatedProperties` KProperty를 받아온다.
    * `his.myAge$delegate`로부터 `.xxxValue()`로 가져온 값을 반환한다.

> 궁금증. KProperty는 무엇일까? 왜 이를 가져온 var3는 왜 참조되지 않았을까? 뭔가 빠진건가? var2는 또 어디간건가??? 오타칠까봐 넓게 띄워놓은건가 😃 

## KProperty

일단 lazy가 적용된 필드에 따라 참조하는 `$$delegatedProperties`의 인덱스가 늘어나는 것을 볼 수 있다.

```kotlin
class Demo {
    val myAge : Int by lazy { 40 }
    val myName : String by lazy { "cwdoh" }
}
```

```java
   public final int getMyAge() {
      Lazy var1 = this.myAge$delegate;
      KProperty var3 = $$delegatedProperties[0];
      return ((Number)var1.getValue()).intValue();
   }

   @NotNull
   public final String getMyName() {
      Lazy var1 = this.myName$delegate;
      KProperty var3 = $$delegatedProperties[1];
      return (String)var1.getValue();
   }
```

`$$delegatedProperties`는 아래와 같이 선언된다.

```java
static final KProperty[] $$delegatedProperties = new KProperty[] {
   (KProperty)Reflection.property1(
      new PropertyReference1Impl(
         Reflection.getOrCreateKotlinClass(Demo.class),
         "myAge",
         "getMyAge()I"
         )
      ),
   (KProperty)Reflection.property1(
      new PropertyReference1Impl(
         Reflection.getOrCreateKotlinClass(Demo.class),
         "myName",
         "getMyName()Ljava/lang/String;"
         )
      )
};
```

대충 내부에 실제 prop.의 구현체로 보이는 `PropertyReference1Impl`를 생성해서 붙이는데, 인자로 넘어간 것은 owner 클래스, prop명, 메소드 시그니처 순이다. (시그니처로 직접 자바 리플렉션을 할 수 있었던가? 아니었던 것 같은데, JNI라도 쓰는건가-_-)

중간에 코드를 따라가봐도 대부분의 코드가 필드가 정의된 환경을 기록 사용하기 위한 코드로 구성되어 있다. 결국 KProperty가 여기에서 하는 일은 kotlin prop 자체를 표현하는 것이다.

요약하면, 내부적으로는 필드의 구성 요소(owner class, 필드명, getter의 named signature)를 풀어서 KProperty[] 타입의`$$delegatedProperties`라는 정적 필드로 가지고 있는 것이다. 아까 궁금했던 `왜 이를 가져온 var3는 왜 참조되지 않았을까`는 **좀 더 케이스를 찾으면 이 정보를 이용하여 상속 내지는 다른 처리를 하는 경우에서 확인할 수 있을 것 같다.**

## Lazy

* https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/lazy.html

lazy는 기본적으로 스레드 안전 모드([LazyThreadSafetyMode.SYNCHRONIZED](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy-thread-safety-mode/-s-y-n-c-h-r-o-n-i-z-e-d.html))와 [Initializer](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/lazy.html#kotlin$lazy(kotlin.Function0((kotlin.lazy.T)))/initializer)를 설정한 객체를 리턴한다.

* 스레드에 안전하다는 것은 `synchronized`라는 말이고, 코드를 보아 초기화 과정에서 단 한번 실행된다고 해석해도 좋을 것 같다.
* initialzier는 실제 구현체가 여러가지가 있는데, 결국은 주어진 초기화 람다 블록을 호출하는 역할을 한다.
    * SynchronizedLazyImpl: synchronized에서 알 수 있듯이 하나의 스레드에서만 initializer에 접근이 가능하며 실행되고, 값이 설정된다.
    * UnsafeLazyImpl: initialized가 되지 않은 경우 무조건 initialzer를 실행하여 값을 기록한다. 따라서 멀티스레딩에서는 안전하지 않다. NPE가 발생가능하다는 얘기
    * InitializedLazyImpl: 값으로 바로 기록된 경우에 사용될 듯 하다.
    * SafePublicationLazyImpl: 여러 스레드에서 동시에 호출될 수 있다. 물론 전부 혹은 일부의 스레드들에서 초기화 블록도 동시에 실행이 가능하다. 다만, 다른 스레드에서 이미 초기화된 값이 설정되었다면 그냥 그 값을 리턴한다.

### SynchronizedLazyImpl

SynchronizedLazyImpl 이 바로 우리가 전달한 람다를 초기화 모듈로 사용하는 부분이다.

```kotlin
private object UNINITIALIZED_VALUE

private class SynchronizedLazyImpl<out T>(initializer: () -> T, lock: Any? = null) : Lazy<T>, Serializable {
    private var initializer: (() -> T)? = initializer
    @Volatile private var _value: Any? = UNINITIALIZED_VALUE
    // final field is required to enable safe publication of constructed instance
    private val lock = lock ?: this

    override val value: T
        get() {
            val _v1 = _value
            if (_v1 !== UNINITIALIZED_VALUE) {
                @Suppress("UNCHECKED_CAST")
                return _v1 as T
            }

            return synchronized(lock) {
                val _v2 = _value
                if (_v2 !== UNINITIALIZED_VALUE) {
                    @Suppress("UNCHECKED_CAST") (_v2 as T)
                }
                else {
                    val typedValue = initializer!!()
                    _value = typedValue
                    initializer = null
                    typedValue
                }
            }
        }

    override fun isInitialized(): Boolean = _value !== UNINITIALIZED_VALUE

    override fun toString(): String = if (isInitialized()) value.toString() else "Lazy value not initialized yet."

    private fun writeReplace(): Any = InitializedLazyImpl(value)
}
```

* `initializer`필드로 전달된 람다를 가진다.
* `_value` 필드에 값을 기록하는데 초기값은 `UNINITIALIZED_VALUE`이다. 결국 아직 액세스가 되지 않은 상황
* 최초의 `get()`이 일어나면, `UNINITIALIZED_VALUE`인지 본다.
  * 당연히 한번 실행은 했다면 값이 `UNINITIALIZED_VALUE`가 아니니까 바로 리턴이 일어난다.
  * 최초 실행이면 일단 synchronized를 타게 되는데, 혹여 이미 초기화가 끝났을 수도 있으므로, 한번 더 `UNINITIALIZED_VALUE` 여부를 체크해서 값이 있으면 그냥 리턴한다. (음...)
  * 정말 아직까지 초기화가 되어 있지 않다면, 람다식을 처리하고 반환값을 초깃값으로 세팅한다. 그리고 이제 불필요한 메모해뒀던 initializer는 null로 초기화된다.

> 근데, bytecode에는 내 초기값이 보이는데, 왜 decompiled java 코드에는 사라졌는가. 찾아보기 귀찮아서 일단 여기에서 턴을 마치기로 한다. ~디컴파일 코드에서 나이가 없어져서 기쁘다. -_-~
> `var3`와 관련된 케이스도 다음 턴으로 미뤄둔다.

**Comment by cwdoh** [comment]
'out'이라는 키워드가 뭐하는 찾아보려 했으나 이는 제네릭을 살펴봐야할 것 같다. ㅜ

**Comment by taehwandev** [comment]
in T : Java의 ? super T에 해당하고, input의 약자입니다.
out T : Java의 ? extends T에 해당하고, output의 약자입니다.

입니다. by thdev.tech .. 제 블로그에 정리해뒀지만 링크는 없음

**Comment by cwdoh** [comment]
Generic도 많이 안써봐서요. ㅋㅋㅋ 그나저나 in/out 이라니...이해하기 어렵...상속의 파이프라인 따라서 정의한건가

**Comment by enshahar** [comment]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy/ 에 보시면 `getValue`가 
`operator fun <T> Lazy<T>.getValue(    thisRef: Any?,     property: KProperty<*>): T`
라고 선언되어 있습니다. 

바이트코드를 직접 디어셈블 해보면 

```
Lazy var1 = this.myAge$delegate;
Object var2  = this
KProperty var3 = $$delegatedProperties[0];
return ((Number)var1.getValue()).intValue();
```

이런식으로 가는데 아마도 `var2`와 `var3`는 `Lazy`의 `getValue`에 맞춰 값을 준비하는 코드가 기계적으로 들어간 것 같습니다. 그런데 이번 경우에는 `getValue()`가 특별한 프로퍼티를 요구하지 않고 정수를 직접 변환하면 되는거라서 그냥 그 두 변수는 무시되는듯. 프로퍼티 타입에 따라서는 `aload_2`와 `aload_3`를 해서 스택에 `var2`와 `var3`를 푸시한 다음에 `invokeinterface`를 사용했을 것 같네요.

**Comment by enshahar** [comment]
그리고 나이 40살은 Demo$myAge$2.class 에 따로 있습니다. ^^

**Comment by cwdoh** [comment]
@enshahar 궁금한 부분이었는데, 고맙습니다.
Decompiled만 보지말고 bytecode의 클래스명도 살펴보는 습관을 가져야겠군요. :)

[update] 다른 클래스도 밑에 있군요! ㅎㅎㅎ

**Comment by taehwandev** [comment]
결국 자바처럼 ()해주는군요 ㅋㅋ

**Comment by cwdoh** [comment]
### TODO: `by`의 좀더 정확한 의미에 대해서 정리해보기 -> #25

* [Delegation](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.properties/-delegates/)

> The by-clause in the supertype list for Derived indicates that b will be stored internally in objects of Derived and the compiler will generate all the methods of Base that forward to b.
