### ISSUE TITLE
[Note] Android Studio Dependency > implementation/compile

### ISSUE THREAD

**Issue by Pluu** [kotlin-korea/Study-Log#28]
Android Studio 3.0 부터 추가된 `implementation`과 기존 `compile`에 대한 이야기입니다

## Stackoverflow

What's the difference between implementation and compile in gradle : https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

```
dependencies {
    api 'commons-httpclient:commons-httpclient:3.1'
    implementation 'org.apache.commons:commons-lang3:3.5' 
}
```

> Dependencies appearing in the api configurations will be transitively exposed to consumers of the library, and as such will appear on the compile classpath of consumers.
>
>Dependencies found in the implementation configuration will, on the other hand, not be exposed to consumers, and therefore not leak into the consumers' compile classpath. This comes with several benefits:
>
> dependencies do not leak into the compile classpath of consumers anymore, so you will never accidentally depend on a transitive dependency
faster compilation thanks to reduced classpath size
less recompilations when implementation dependencies change: consumers would not need to be recompiled
cleaner publishing: when used in conjunction with the new maven-publish plugin, Java libraries produce POM files that distinguish exactly between what is required to compile against the library and what is required to use the library at runtime (in other words, don't mix what is needed to compile the library itself and what is needed to compile against the library).
The compile configuration still exists but should not be used as it will not offer the guarantees that the api and implementation configurations provide.

## Gradle

48.2. API and implementation separation : https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

## Android Studio 

Use the new dependency configurations : https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations

> The dependency is available to the module at compile time, and it's available to the consumer of the module only at runtime. For large multi-project builds, using implementation instead of api/compile can result in significant build time improvements because it reduces the amount of projects that the build system needs to recompile. Most app and test modules should use this configuration.

## Google I/O

https://youtu.be/7ll-rkLCtyk?t=22m20s

> Speeding Up Your Android Gradle Builds (Google I/O '17)

**Comment by SeongUgJung** [comment]
api 는 매번 빌드를 하겠다는 것이고
implementation 은 빌드된 것을 재사용하겠다는 의미 아닌가요?

**Comment by cwdoh** [comment]
그렇게도 볼 수 있겠네요. :)

---
혹시 이 이슈를 보시는 분들을 위해 제가 이해하는 바를 적어봅니다.

* 모듈A 내에 선언된 api dep.는 모듈A를 사용하는 쪽에도 노출됨을 전제
* 모듈A 내에 선언된 implementation dep.은 모듈A 내에서만 완전 포함, 사용측에는 알 필요가 없음

굳이 비교하자면  implementation을 wrapping된 형태로 볼 수 있고, api의 경우 composition으로 볼 수 있음. 따라서, implementation으로 선언된 경우는 해당 dep.가 재빌드/갱신되지 않은 경우라면 그대로 재사용되고, 이로 인한  종속 관계에서 상위(사용측)에 별다른 영향을 주지 않도록 함.

tl;dr: 상위(사용측) 모듈에서 특정 dep. 감춰지는 포함 관계가 성립할 때 implementation을 통해 빌드 성능을 향상

right?

**Comment by Pluu** [comment]
https://blog.mindorks.com/implementation-vs-api-in-gradle-3-0-494c817a6fa
여기 그래프 글에 의해서도 비슷한 설명이 되어있네요

실제 모듈과의 연결이 깊은경우에 해당 효과를 볼지도 모르겠네요
하지만 우리는 라이브러리를 여러쓰니 implementation 사용시 기본적인 효과는 볼듯
이미 버전변경을 하지않는 경우에는 재빌드 필요가 없으니

**Comment by Pluu** [comment]
https://sikeeoh.github.io/2017/08/28/implementation-vs-api-android-gradle-plugin-3/
누군가 번역해서 올림
Implementation  하면 일부 모듈에 직접 접근을못하기도 하네요
