### ISSUE TITLE
[Article] Migrating an Android project to Kotlin

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#3]
["Migrating an Android project to Kotlin” @keyboardsurfer](https://medium.com/google-developers/migrating-an-android-project-to-kotlin-f93ecaa329b7)

topeka를 코틀린으로 컨버팅하면서 얻은 인사이트를 공유하는 글입니다.

* 늦은 assign으로 인한 nullable 처리는 lateinit로 :)
* `?:` 연산자로 if null -> create 형식의 코드를 가독성있게 줄이기
* setter/getter 위주의 필드 처리는 data class로
* Objective C의 category에서의 구현처럼 [extension function](https://kotlinlang.org/docs/reference/extensions.html)을 이용해서 특정 클래스에 대한 구현 패턴을 특정 클래스의 메소드처럼 확장하여 사용
* 혹은 고차함수(Higher order functions)를 이용하여 동작 패턴을 단순화

**Comment by smalljiny** [comment]
안녕하세요.
정진철(Mario)입니다.

좋은 글 공유 감사드립니다.
꼭 읽어 보고 학습에 참고하도록 하겠습니다.

행복한 일주일 시작하시기 바랍니다.

**Comment by Pluu** [comment]
이럴때야말로 아래 링크들을
- [코틀린의 유용한 함수들 - let, apply, run, with](http://kunny.github.io/lecture/kotlin/2016/07/06/kotlin_let_apply_run_with/)
- [let, with, run, apply, use(using)](http://blog.import.re/post/kotlin-let-apply-run-with-use/)
