### ISSUE TITLE
[Note] Android O 와 Kotlin Android Extensions 사용시 findViewById 문제

### ISSUE THREAD

**Issue by Pluu** [kotlin-korea/Study-Log#32]
Kotlin || Not able to “findViewById” in Kotlin. Getting error “Type inference failed”
https://stackoverflow.com/questions/44950401/kotlin-not-able-to-findviewbyid-in-kotlin-getting-error-type-inference-fa

기존 Android 개발에서는 `findViewById` 사용 후 해당 타입으로 캐스팅해줘야했지만,
Android O 부터는 View의 Generic으로 사용되어 Kotlin Android Extensions과 사용시 타입에 대한 추론이 불가능해지는 문제가 생김. (View가 아닌 T가 됨)

> val recycler_view =  findViewById(R.id.recycler_view) as RecyclerView ///IN THIS LINE I AM GETTING THE ERROR

아래로 타입 확정해서 처리 가능
> val recycler_view = findViewById< RecyclerView >(R.id.recycler_view)

**Comment by snowflake-1117** [comment]
맨 아랫줄에 있는 코드
`val recycler_view = findViewById(R.id.recycler_view)`
에서
`<RecyclerView>`
가 빠져 있는 것 같습니당~

**Comment by Pluu** [comment]
@snowflake-1117 깃허브가 이렇게하면 < RecyclerView > 를 숨겨버리네요 ㅠㅠ

**Comment by snowflake-1117** [comment]
@Pluu 아하 그랬군요 😆

**Comment by cwdoh** [comment]
코드블럭이 아닌 마크다운에서 ```\<RecyclerView\>``` 로 표기하면 \<RecyclerView\> 로 나옵니다. :)
