### ISSUE TITLE
[SundaySadang] 4회차 모임 공지

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#33]
**8월 6일은 스터디의 공식 휴무일입니다. :)**

이번 4회차 모임은 아래 사항 참조하셔서 참여 부탁드립니다.

- 시간
    - 8월 13일(일요일) 오전 10시 30분 ~ 약 2시간
- 장소
    - [사당 모임(MoiM 2호점)](http://www.moimstudy.com/03.html)
    - 예약자 명: 도창욱
    - 약도: http://naver.me/57vjvRia
- 준비물
    - 안드로이드 스튜디오(3.0 권장)가 설치된 노트북
    - 각자 음료수 비용
    - 대관비 : 최소 3000원 + 알파
        - 대관비는 참여자 수 및 프로젝터 대여에 따라 일부 조정이 필요할 수 있습니다.

금주 Agenda는 아래와 같이 진행할 예정입니다.
- Pull Request 리뷰
    - 각자의 PR에 있는 커밋 코드에 대해 설명합니다.
        - 굳이 전체를 설명할 필요는 없습니다.
        - 본인이 효과적이라고 생각한 부분이나 의구심이 드는 파트에 대해 설명합니다.
        - 필요하다면 코드 흐름을 추가 설명할 수 있습니다
    - 참가자들은 리뷰 시에 의견을 개진하고, 이를 PR에 코멘트합니다.
- 기타 읽어볼만한 글이나 내용들이 있으면 공유합니다.

참가가 불가능할 경우 미리 연락주세요.

# 참석 예정 표시

- [x] @cwdoh
- [x] @Pluu 
- [x] @whylee259 
- [x] @tonyjs 
- [x] @moka-a
- [x] @snowflake-1117 
- [x] @soulduse 
- [ ] @chonamdoo 
- [ ] @tak8997 
- [x] @lynring24 
- [ ] @HUFSCSE 

## 개인 사정 불참

- [ ] @omjoonkim 

- [ ] @LeeKangUk

빠지신 분은 아래에 코멘트 부탁드립니다.

**Comment by omjoonkim** [comment]
그날 휴가를가서 참석 못할 것 같습니다😭

**Comment by cwdoh** [comment]
@omjoonkim YOLO! 잘 다녀오세요. :)

**Comment by LeeKangUk** [comment]
저도 휴가 때문에 다음주에 뵙겠습니다!

**Comment by cwdoh** [comment]
@LeeKangUk 님도 잘 다녀오세요! :)

**Comment by heongkyun** [comment]
저는 부모님 올라오셔서 참석 못 할 것 같습니다ㅠ 다음주에 뵙겠습니당ㅎ

**Comment by cwdoh** [comment]
* 대관비 + 빔프로젝터: 34,000원 / 8 = 4,250원
* 5회는 스터디 장소를 변경할까 합니다. 지금 장소는 지리적인 부분 외에는 큰 장점이 없어보이네요. 의견 부탁합니다.
