### ISSUE TITLE
[Note] Coroutine

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#42]
## links

* [Coroutines](https://kotlinlang.org/docs/reference/coroutines.html)
* [Tutorial](https://kotlinlang.org/docs/tutorials/coroutines-basic-jvm.html)
* [Coroutine guideline](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md)
* [Github implementation](https://github.com/Kotlin/kotlin-coroutines)

## articles

* [A first walk into Kotlin coroutines on Android](https://android.jlelse.eu/a-first-walk-into-kotlin-coroutines-on-android-fe4a6e25f46a)
* [Android Coroutines with Kotlin: getting rid of runOnUiThread and Callbacks; cleaner thread handling; and more](https://medium.com/@macastiblancot/android-coroutines-getting-rid-of-runonuithread-and-callbacks-cleaner-thread-handling-and-more-234c0a9bd8eb)

## todo

코틀린은 실행 환경의 지원여부와 관계없이 coroutine을 지원하기 위해 실행 지점을 모두 state-machine의 형태로 관리한다(고 적혀있다). 대략적으로 공유되는 컨텍스트의 저장공간을 포함한 최상위 클래스가 machine으로써 존재하고, 각각의 coroutine이 각각의 inner 클래스 혹은 fun(아마 이거겠지)으로 존재할 것 같다. 일단 생성되는 jvm 코드 형태를 살펴보고 kotlin의 코루틴 디자인에 대해 유추해볼 것.

**Comment by cwdoh** [comment]
## keyword `suspend`

훑어본 상태지만 suspend 키워드는 어쨌던 중단/재개 지점으로 사용될 coroutine을 지정하는 의미가 되는 것 같다. suspend가 적용된 함수는 다른 suspend 혹은 코루틴에서 호출되어야 하는데, 왜인지는 나중에 고민하기로 한다.

> async 등을 먼저 보고 싶었지만, 디컴파일이 되지 않는다. 이유는 나중에 찾는다. ㅋ 

```kotlin
class CoroutineDemo {
    suspend fun suspendFun() { println("suspension!") }
    fun normalFun() { println("just b") }

    suspend fun test() {
        suspendFun()
        normalFun()
    }
}
```

> 코드를 변환해보면 대충 아래와 같이 생성된다. 비슷한 내용은 [여기를 참고](https://kotlin.link/articles/Bytecode-behind-coroutines-in-Kotlin.html)해도 괜찮다.

```java
public final class CoroutineDemo {
   @Nullable
   public final Object suspendFun(@NotNull Continuation $continuation) {
      Intrinsics.checkParameterIsNotNull($continuation, "$continuation");
      String var2 = "suspension!";
      System.out.println(var2);
      return Unit.INSTANCE;
   }

   public final void normalFun() {
      String var1 = "just b";
      System.out.println(var1);
   }

   @Nullable
   public final Object test(@NotNull Continuation $continuation) {
      Intrinsics.checkParameterIsNotNull($continuation, "$continuation");
      return (new CoroutineImpl($continuation) {
         @Nullable
         public final Object doResume(@Nullable Object var1, @Nullable Throwable throwable) {
            Object var3 = IntrinsicsKt.getCOROUTINE_SUSPENDED();
            switch(super.label) {
            case 0:
               if(throwable != null) {
                  throw throwable;
               }

               CoroutineDemo var10000 = CoroutineDemo.this;
               super.label = 1;
               if(var10000.suspendFun(this) == var3) {
                  return var3;
               }
               break;
            case 1:
               if(throwable != null) {
                  throw throwable;
               }
               break;
            default:
               throw new IllegalStateException("call to 'resume' before 'invoke' with coroutine");
            }

            CoroutineDemo.this.normalFun();
            return Unit.INSTANCE;
         }
      }).doResume(Unit.INSTANCE, (Throwable)null);
   }
}
```

간단하게 보면, suspend가 적용된 함수는 `Continuation`을 가지는 메소드로 변환되었음을 확인할 수 있다. 자세히는 봐야겠지만 아마 요놈은 내부의 코드를 재개하기 위한 어떤 상태값들의 매개체가 될 것으로 예상할 수 있다.

동일하게 suspend를 가지는 suspendFun()과 test()의 내부 구현에는 차이가 있는데, suspend fun을 포함하는 경우는 CoroutineImpl을 구현한 객체를 생성한다. doResume() 내에 어떤 값에 의해 suspendFun()를 호출하는 부분 혹은 exception을 처리하고 있다. 아마 suspend fun이 늘어나면 이를 처리하는 로직이 비슷한 방식으로 전개될 것 같다.

이쯤에서 다음 TODO & 키워드를 정리하고, 턴을 넘긴다.

* Continuation
* CoroutineImpl
* 복잡한 코드의 전개
* 변수를 넘기는 경우에 대한 처리

**Comment by cwdoh** [comment]
### Deferred

* 논블로킹 + 취소 가능한 인터페이스
> Deferred value is a non-blocking cancellable future.

Deferred의 값은 다음과 같은 상태를 가진다.

| **State**                        | [isActive] | [isCompleted] | [isCompletedExceptionally] | [isCancelled] |
| -------------------------------- | ---------- | ------------- | -------------------------- | ------------- |
| _New_ (optional initial state)   | `false`    | `false`       | `false`                    | `false`       |
| _Active_ (default initial state) | `true`     | `false`       | `false`                    | `false`       |
| _Resolved_  (final state)        | `false`    | `true`        | `false`                    | `false`       |
| _Failed_    (final state)        | `false`    | `true`        | `true`                     | `false`       |
| _Cancelled_ (final state)        | `false`    | `true`        | `true`                     | `true`        |

* 기본적으로는 _active_ 상태에서 _resolved_, _failed_, _cancelled_ 로 전환
* CoroutineStart.LAZY 로 시작할 경우는 _new_ 로 시작한다. (당연히 실제로 실행이 시작된 상태는 아니므로...)

### async

Deferred 반환하는 구현체

```kotlin
/**
 * Creates new coroutine and returns its future result as an implementation of [Deferred].
 * ...
 */
public fun <T> async(
    context: CoroutineContext,
    start: CoroutineStart = CoroutineStart.DEFAULT,
    block: suspend CoroutineScope.() -> T
): Deferred<T> {
    val newContext = newCoroutineContext(context)
    val coroutine = if (start.isLazy)
        LazyDeferredCoroutine(newContext, block) else
        DeferredCoroutine<T>(newContext, active = true)
    coroutine.initParentJob(context[Job])
    start(block, coroutine, coroutine)
    return coroutine
}
```

1. 전달된 coroutineContext를 새로운 coroutineContext로 wrapping 하는 듯
2. lazy 여부에 따라 `LazyDeferredCoroutine` 혹은 `DeferredCoroutine`를 생성한다.
3. 부모 잡을 초기화(아마도 저장)한다. 전달된 context의 현재 동작은 context 내에 key `Job`에 저장되어 있는 듯
4. 받은 block으로 coroutine을 시작한다.
5. 시작된 coroutine을 반환한다.

아마도 CoroutineContext를 통해 현재 실행 중인 정보를 저장하고, Async가 중첩된다면 전달된 context를 Parent로 참조하는 형태로 중첩을 처리하는 듯 하다.
* 필요에 따라 실행을 연기(defer)할 수 있는데 이는 다음턴으로...

**Comment by tonyjs** [comment]
[suspend 공식 링크](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#coroutine-basics) 를 보고 내부 메소드 전부 `suspend` 키워드가 달려야 하는 건, 유추하건데(이건 정말 아마도) `중지` 에 초점이 맞춰져 있는 것 같아요.
상황에 따라 중지 될 수 도 있는 메소드 안에 `중지불가`한 행동이 있다면 어불성설이 되니까...?

**Comment by cwdoh** [comment]
아, 저는 `suspend fun은 다른 suspend fun 혹은 coroutine으로부터만 호출될 수 있다.`는 말이 헷갈렸었었어요.

정확히는 코루틴과 관련한 키워드가 suspend만 존재하는 상황에서 `다른 coroutine`은 무슨 말인가 하는 의문이 들었었습니다. 이제보니 `fun <T> async(block: suspend () -> T)`와 같은 레귤러 함수가 인자로 suspend fun을 받아 처리하는 것을 coroutine이라고 같이 불러버리네요. ㅋ

시간을 아끼기 위해 [해당 부분](https://kotlinlang.org/docs/reference/coroutines.html#suspending-functions)을 발췌해보자면...

> Suspending functions can take parameters and return values in the same manner as regular functions, but they can only be called from coroutines and other suspending functions. In fact, to start a coroutine, there must be at least one suspending function, and it is usually anonymous (i.e. it is a suspending lambda). Let's look at an example, a simplified async() function (from the kotlinx.coroutines library):
> ```kotlin
> fun <T> async(block: suspend () -> T)
> ```
> Here, **async() is a regular function** (not a suspending function), but the block **parameter has a function type with the suspend modifier**: suspend () -> T. So, when we pass a lambda to async(), it is a suspending lambda, and **we can call a suspending function from it**:

**Comment by tonyjs** [comment]
[anko 에서의 coroutine 예](https://github.com/Kotlin/anko#anko-layouts-wiki) 에서 보면

> onClick accepts a suspend lambda, so you can write your asynchronous code right inside the listener! 

라고 되어 있다.

직접 코드를 보면
```kotlin
fun android.view.View.onClick(
        context: CoroutineContext = UI,
        handler: suspend CoroutineScope.(v: android.view.View?) -> Unit
) {
    setOnClickListener { v ->
        launch(context) {
            handler(v)
        }
    }
}
```
이런식으로 구현이 되어 있다. (기본 구현이 이렇게 되어 있으니 `onClick` 구문에서 많은 양의 일을 해도 UI가 블락되진 않을 듯)

`CoroutineContext = UI` 쪽을 살펴보면 `CoroutineContext` 는 interface 이고 이것의 구현체를 어떻게 만드냐에 따라서 어떤 스레드에서 동작할지 만들어 줄 수 있는가보다. 살펴보니 그렇다. Java concurrent Executors 쪽에서 제공해주는 녀석들과 비슷하다. 

Name | Description
-- | --
CommonPool | Confines coroutine execution to a shared pool of threads
newSingleThreadContext | Create new single-threaded coroutine context
newFixedThreadPoolContext | Creates new thread pool of a fixed size
Executor.asCoroutineDispatcher | Extension to convert any executor
Unconfined | Does not confine coroutine execution in any way

`UI` 를보면 우리가 안드로이드 프로그래밍을 하면서 늘 보던 `Handler` 를 이용해 구현이 되어있다. 
`val UI = HandlerContext(Handler(Looper.getMainLooper()), "UI")` 요렇게 생겼다. 

`launch` 는 자세히는 더 봐야 알겠지만 `coroutine` 의 시작이다.
```kotlin
public fun launch(
    context: CoroutineContext,
    start: CoroutineStart = CoroutineStart.DEFAULT,
    block: suspend CoroutineScope.() -> Unit
): Job {
    val newContext = newCoroutineContext(context)
    val coroutine = if (start.isLazy)
        LazyStandaloneCoroutine(newContext, block) else
        StandaloneCoroutine(newContext, active = true)
    coroutine.initParentJob(context[Job])
    start(block, coroutine, coroutine)
    return coroutine
}
```

`handler: suspend CoroutineScope.(v: android.view.View?)` 여기서는 `coroutine` 안에서 어떤 행동을 해줄지 정의해주는 부분이다.

직접 `Coroutine` 을 여는 `function` 을 만들고 싶다면 이런식으로 구현하면 되겠다.

**Comment by cwdoh** [comment]
## coffee talk memo

> 오전에 @tonyjs 님과 가졌던 커피톡의 미제사건(?)들 메모

### coroutines..

* async는 반환값이 존재하는 함수 형태로 쓰는데 적합한 듯
* launch는 흐름을 제어(실행/대기 등)하는 역할로...

> 다른 적합한 사례가 있는지 보도록 하자.

* cancel은 suspend 단위로되는 듯 하다. 일반적인 제어구(loop 등)은 `isActive`를 구현부에서 처리하자

[Unconfined vs confined dispatcher](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#unconfined-vs-confined-dispatcher)

> `Unconfined` 예제에서 튀어나온 `kotlinx.coroutines.DefaultExecutor`는???

[Children of a coroutine](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#children-of-a-coroutine)

> cancel의 동작이 헷갈림

**Comment by cwdoh** [comment]
[“What are Coroutines in Kotlin?” @amitiitbhu](https://blog.mindorks.com/what-are-coroutines-in-kotlin-bf4fecd476e9)

**Comment by cwdoh** [comment]
from [kotlin-coroutines](https://github.com/Kotlin/kotlin-coroutines)

## Navigate

* [Description of the current implementation](kotlin-coroutines-informal.md) (KEEP for Kotlin Coroutines)
* [Coroutines support library for Kotlin](https://github.com/kotlin/kotlinx.coroutines) (`kotlinx.coroutines`)

## Videos and presentations

* From a user standpoint:
   * [Introduction to Coroutines](https://www.youtube.com/watch?v=_hfBv0a09Jc) (Roman Elizarov at KotlinConf 2017, [slides](https://www.slideshare.net/elizarov/introduction-to-coroutines-kotlinconf-2017))
   * [Deep dive into Coroutines](https://www.youtube.com/watch?v=YrrUCSi72E8) (Roman Elizarov at KotlinConf 2017, [slides](https://www.slideshare.net/elizarov/deep-dive-into-coroutines-on-jvm-kotlinconf-2017))
* Language design overview:
  * Part 1 (prototype design): [Coroutines in Kotlin](https://www.youtube.com/watch?v=4W3ruTWUhpw) 
    (Andrey Breslav at JVMLS 2016)
  * Part 2 (current design): [Kotlin Coroutines Reloaded](https://www.youtube.com/watch?v=3xalVUY69Ok&feature=youtu.be) 
    (Roman Elizarov at JVMLS 2017, [slides](https://www.slideshare.net/elizarov/kotlin-coroutines-reloaded)) 
* Lock-Free Algorithms for Kotlin Coroutines 
   [part 1](https://www.youtube.com/watch?v=W2dOOBN1OQI) &
   [part 2](https://www.youtube.com/watch?v=iQsN_IDUTSc) 
   (Roman Elizarov at SPTCC 2017, [slides](https://www.slideshare.net/elizarov/lockfree-algorithms-for-kotlin-coroutines))

**Comment by cwdoh** [comment]
[CoroutineContext](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines.experimental/-coroutine-context/index.html)
> Persistent context for the coroutine. It is an indexed set of Element instances. An indexed set is a mix between a set and a map. Every element in this set has a unique Key. Keys are compared by reference.

* [interface](https://github.com/JetBrains/kotlin/blob/1.2.30/libraries/stdlib/src/kotlin/coroutines/experimental/CoroutineContext.kt#L25)

[Continuation](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines.experimental/-continuation/index.html)
* [intertface: Continuation](https://github.com/JetBrains/kotlin/blob/1.2.30/libraries/stdlib/src/kotlin/coroutines/experimental/Coroutines.kt#L23)

**Comment by cwdoh** [comment]
* [HelperContext: UI](https://github.com/Kotlin/kotlinx.coroutines/blob/fcdce10143103fb5418e6247abfd44fd8ff941ef/ui/kotlinx-coroutines-android/src/main/kotlin/kotlinx/coroutines/experimental/android/HandlerContext.kt#L29)

**Comment by cwdoh** [comment]
* [How Coroutine works](https://medium.com/@2f62260f33f7/789291da6a50)
