### ISSUE TITLE
[Note] 4회차 mentioned keywords

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#43]
* java interface (SAM)을 kt에서 직접 사용할 때는 문제가 없는데...kt interface일 때는 왜 문제가 생기는가?

> jvm sdk version(1.8)에 따라 다르지 않을까? @Pluu 

* invoke()

> [operator 관련 글](http://chintanrathod.com/chapter-3-working-with-operators-in-kotlin-android/) 참조합시다. @cwdoh

**Comment by tonyjs** [comment]
[interface 관련 이슈 링크](https://youtrack.jetbrains.com/issue/KT-7770)

[공식사이트문서](https://kotlinlang.org/docs/reference/java-interop.html#sam-conversions) 아래쪽을 보면 이렇게 기술되어 있네요.

> Also note that this feature works only for Java interop; since Kotlin has proper function types, automatic conversion of functions into implementations of Kotlin interfaces is unnecessary and therefore unsupported.

**Comment by cwdoh** [comment]
@tonyjs 어제 이슈가 이것이었나요. 어제 정상 컨디션이 아니라서 기억이...;;;

**Comment by tonyjs** [comment]
@cwdoh Kotlin 으로 만든 interface 는 lambda 가 적용이 안되고
```
object : Listener {
   override ...
```
이런식으로 써야하는 반면 Java 는 labmda 가 적용이 안되는 것인가? 
아니었나요??ㅜㅜ

**Comment by cwdoh** [comment]
@tonyjs 그랬던 것 같네요! :)

**Comment by Pluu** [comment]
우선 호출하는곳이 Fragment에서 activity의 메소드를 직접부르는것이라서 더 안되는 문제일듯해요
