### ISSUE TITLE
[SundaySadang] 5회차 모임 공지

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#44]
이번 5회차 모임은 아래 사항 참조하셔서 참여 부탁드립니다.

- 시간
    - 8월 20일(일요일) 오전 10시 30분 ~ 약 2시간
- 장소
    - 미정
- 준비물
    - 안드로이드 스튜디오(3.0 권장)가 설치된 노트북
    - 각자 음료수 비용
    - 대관비 + 알파
        - 대관비는 참여자 수 및 프로젝터 대여에 따라 일부 조정이 필요할 수 있습니다.

금주 Agenda는 아래와 같이 진행할 예정입니다.
- Pull Request 리뷰
    - 각자의 PR에 있는 커밋 코드에 대해 설명합니다.
        - 굳이 전체를 설명할 필요는 없습니다.
        - 본인이 효과적이라고 생각한 부분이나 의구심이 드는 파트에 대해 설명합니다.
        - 필요하다면 코드 흐름을 추가 설명할 수 있습니다
    - 참가자들은 리뷰 시에 의견을 개진하고, 이를 PR에 코멘트합니다.
- 기타 읽어볼만한 글이나 내용들이 있으면 공유합니다.

참가가 불가능할 경우 미리 연락주세요.

# 참석 예정 표시

- [x] @cwdoh
- [x] @whylee259 
- [x] @tonyjs 
- [x] @moka-a
- [ ] @chonamdoo 
- [ ] @tak8997 
- [x] @HUFSCSE 
- [ ] @LeeKangUk

## 개인 사정 불참

- [ ] @Pluu 
- [ ] @soulduse 
- [ ] @snowflake-1117 
- [ ] @lynring24 
- [ ] @omjoonkim 

빠지신 분은 아래에 코멘트 부탁드립니다.

**Comment by cwdoh** [comment]
## I need your help!!

사당역 주변에 괜찮은 스터디룸이 보이지가 않는데요. 장소에 대한 의견 주시면 감사하겠습니다.
> ~이번 주에는 조금 멀지만 기업 탐방을 겸해서 야놀자??~

**Comment by soulduse** [comment]
고향 내려가서 이번주는 참석 못할것 같습니다 ^^

**Comment by Pluu** [comment]
결혼하는 친구때문에 지방내려가야해서 참석 못할것 같아요
기업탑방은 나중에 ㅎ

**Comment by tonyjs** [comment]
[토즈 교대점](http://map.naver.com/local/siteview.nhn?code=18348261&_ts=1502937658749)

[갭이어 사당점](https://spacecloud.kr/space/2515)

요거 두 개(아마도 이미 보셨겠지만...) 정도만 눈에 들어오는데 이마저도 가격대가 1인당 6천원 정도네요 ㅜㅜ

**Comment by snowflake-1117** [comment]
이번주는 GDG Summer party 행사에 참여하게되어 참석을 못하게 되었습니다.

**Comment by snowflake-1117** [comment]
[히든스페이스 서울대입구](https://spacecloud.kr/space/6886)

조건에 맞는 스터디룸이 별로 없네요
사당에서 그나마 가까운 곳으로 찾아봤는데 여기도 시간(인) 당 2500원 정도 하네요 ㅜㅜ

**Comment by whylee259** [comment]
저도 장소를 저희 회사로 알아봤는데,
갑자기 회사에 이슈가 생겨서 못쓰게 되었네요.

**Comment by lynring24** [comment]
이번주는 GDG Summer party 행사에 참여하게되어 참석을 못하게 되었습니다.  

회의실로 주로 사용되는 공간이라 빔프로젝터는 확실히 되어있는데
최대 인원이 10까지라 애매하네요
[르호봇 사당](http://blog.naver.com/sadangbiz/221060162166)

**Comment by omjoonkim** [comment]
저도 이번주 GDG Summer party 행사 스탶이라 참석 못할 것 같습니다..!😭

**Comment by cwdoh** [comment]
이번주 일요일은 참석하는 분이 많지 않군요.
그럼 이번주 일요일은 정식 모임은 하지 않을까 하는데 어떻게 생각하세요?
오늘 밤까지 의견 모아보고 결정하겠습니다.

**Comment by socar-doga** [comment]
전 찬성합니다!

**Comment by soulduse** [comment]
전 찬성합니다!

**Comment by heongkyun** [comment]
저도 찬성합니당

**Comment by snowflake-1117** [comment]
일요일에 참석가능하신 분들이 괜찮으시다면 저도 찬성합니당

**Comment by whylee259** [comment]
넵 찬성합니다

**Comment by cwdoh** [comment]
네 그러면 금주 스터디 모임은 캔슬하도록 하겠습니다.
