### ISSUE TITLE
[SundaySadang] 마지막 모임 공지

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#45]
이번 5회차 모임은 아래 사항 참조하셔서 참여 부탁드립니다.

- 시간
    - 8월 27일(일요일) 오전 10시 30분 ~ 약 2시간
- 장소
    - 미정
- 준비물
    - 안드로이드 스튜디오(3.0 권장)가 설치된 노트북
    - 각자 음료수 비용
    - 대관비 + 알파
        - 대관비는 참여자 수 및 프로젝터 대여에 따라 일부 조정이 필요할 수 있습니다.

금주 Agenda는 아래와 같이 진행할 예정입니다.
- Pull Request 리뷰
- 마지막으로 공유하고 싶은 내용이나 향후 개별 계획에 대한 얘기

참가가 불가능할 경우 미리 연락주세요.

# 참석 예정 표시

- [x] @cwdoh
- [x] @Pluu 
- [x] @tonyjs 
- [x] @whylee259 
- [ ] @soulduse 
- [x] @snowflake-1117 
- [x] @lynring24 
- [x] @omjoonki
- [x] @moka-a
- [x] @chonamdoo 
- [ ] @tak8997 
- [ ] @HUFSCSE 
- [ ] @LeeKangUk

빠지신 분은 아래에 코멘트 부탁드립니다.

**Comment by steadymoka** [comment]
벌써 마지막이라니 !

**Comment by cwdoh** [comment]
장소는 상황 봐서 고를 예정인데, 일단 [히든스페이스](https://spacecloud.kr/space/6886)와 [스누디](https://spacecloud.kr/space/4348)를 고려 중입니다.
금일까지 참석 여부 정해주시면 좋겠습니다.
그리고, 마지막 모임이니 점심을 ~샤로수길에서~ 같이 해도 좋을 것 같네요. :)

**Comment by cwdoh** [comment]
제가 이전 모임글을 복사하면서 참석여부가 같이 복사되었었네요. 적당히 지워두었는데 다시 한번씩 확인 부탁할께요.

**Comment by cwdoh** [comment]
장소는 서울대입구역 [히든스페이스](https://spacecloud.kr/space/6886)로 예약해두었습니다. 내일 뵈요!!

**Comment by LeeKangUk** [comment]
금일 지방에 내려와있어 참여를 못했는데 공유하는 걸 깜빡 잊었네요..ㅠ
마지막인데 아쉽습니다 다음에 뵈어요!

**Comment by cwdoh** [comment]
정산입니다.

| 항목 | 총액 | 인원 | 개별 비용 |
|---|---|---|---|
| 대관 | 40,000원 | 9 | 4,444.4원 |
| 식사 |  62,500원 | 8 | 7,812.5원 |

> 총합 백원 단위 절삭합니다.

* 스터디 Only(@moka-a 님): 4,000원
* 스터디 + 식사 : 12,000원

> 토스로 보내주셔도 됩니다. :)

정기 오프라인은 오늘로 끝이지만, 말씀드린대로 비정기적인 토픽 논의나 모각코 등은 자유롭게 진행될 예정입니다.
그간 정말 수고들 많으셨어요. :)

**Comment by cwdoh** [comment]
아직 입금 전이신 분들은 위 계좌로 부탁드립니다. :)
