### ISSUE TITLE
[Notice] Kotlin 스터디 모임 발의

### ISSUE THREAD

**Issue by Pluu** [kotlin-korea/Study-Log#56]
안녕하세요 프루입니다.
구 선데이사당 멤버 중 몇명과 신규멤버로 다시 한번 Kotlin 스터디를 시작하려고 합니다

## 스터디 안내

- 주제 : `Kotlin in Action` 책 완독
- 스터디 방식
   1. 일정한 분량을 읽는다
   2. 랜덤으로 발표자를 뽑는다
   3. 발표 한다
- 모이는 일시 : 2018년 2월 24일부터 `매주 토요일 or 일요일 아침 10시`
- 모이는 장소 : 서울대입구역 / 사당 주변 스터디 룸 혹은 어딘가
- 기타 : 이북 / 원서 / 번역서 선택은 자유입니다

※ 모두를 위한 스터디이므로 미준비시 벌금 (1만원) 이 있으며, 이 금액은 추후 뒷풀이용으로 사용 예정입니다.

## 스터디 잡무

- @cwdoh / @Pluu

## 스터디 모집

- 모집인원 : 모집 후 랜덤 추첨 예정입니다
- 기존 구 선데이 사당 X 명 + 신규 멤버 X 명
- 멤버 확정 후 첫 티타임을 가질 예정입니다.

## 신청 등록폼

https://goo.gl/forms/XjlSTuwIg9saG3Ht2

**Comment by cwdoh** [comment]
참석합니다.

* changwook.doh@gmail.com

**Comment by whylee259** [comment]
저도 참석합니다. 

 - whylee259@gmail.com

**Comment by tonyjs** [comment]
참석하겠습니다
* pkojun09@gmail.com

**Comment by hyunji92** [comment]
저두우우우!
 - chunghj09@gmail.com

**Comment by snowflake-1117** [comment]
참석하고싶습니다 :)
1117hyemin@gmail.com

**Comment by soulduse** [comment]
저도 참석하고 싶어요~! :)
developerkhy@gmail.com

**Comment by Pluu** [comment]
어디에도 메일 적으라는 말을 하지않았는데 ㅋㅋㅋ
첫글의  중요성

**Comment by taehwandev** [comment]
저도요

**Comment by Pluu** [comment]
신규 멤버 유입도 할 예정이라는 점 !! 안내해드려요

**Comment by lynring24** [comment]
저도 참석하겠습니다 :)

**Comment by kangkw** [comment]
저도요

**Comment by kyeongwan** [comment]
저도요

**Comment by omjoonkim** [comment]
참석하겠습니다~

**Comment by smalljiny** [comment]
참석하고 싶습니다. (신규)

**Comment by hixguru** [comment]
저도 참가하고 싶습니다! ikxguru@gmail.com

**Comment by dunkindonass** [comment]
참가 신청합니다 dunkindonass@gmail.com

**Comment by Pluu** [comment]
@cwdoh, @whylee259, @tonyjs, @hyunji92, @snowflake-1117, @soulduse, @taehwandev, @lynring24, @kyeongwan, @omjoonkim, @smalljiny, @hixguru, @dunkindonass 댓글로 이렇게까지 될줄 몰라서 등록폼을 오픈했습니다. 귀찮으시더라도 등록폼에 입력 부탁드려요!!

**Comment by Pluu** [comment]
============== 댓글로 신청은 받지않습니다 ==============
