### ISSUE TITLE
[Namsadang/Aries] 스터디 로그

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#58]
* 궁금한 점이나 개인적으로 추가 정리하고 싶은 내용은 이슈를 자유롭게 활용할 수 있다.

## 자료 준비 및 진행

* 발표는 2개의 그룹으로 나누어 번갈아 진행합니다.
* 발표에 참가한 인원은 차주에 쉴(?) 권리가 있습니다.
* 발표 자료는 [namsadang](https://github.com/kotlin-korea/Study-Log/tree/namsadang)에 마크다운으로 올려주시면 됩니다.
* 필요한 경우 자료에 대한 PR을 보내셔도 됩니다.

## 오프라인 룰

* 오프라인 모임에 참여하여야 합니다.
* 오프라인 참석 전 본인이 포함된 차수인 경우 자료 작성에 참여하여야 합니다.
* 오프라인 참여가 불가능할 경우 최소 이틀 전 깃헙 모임 관련 이슈에 참여 불가 의사를 밝히셔야 합니다.
* 오프라인 참여가 3회를 초과하여 불가능할 경우 자동으로 온라인 멤버로 전환됩니다.
* 모임 비용은 비주기라도 일정 금액을 미리 거치하는 형태로 진행합니다.
* 모임에 참석하지 못하시는 경우라도 금액을 환불하지는 않습니다.

**Comment by Pluu** [comment]
## 제가 정리한 내용

1. 매주 발표할 사람을 랜덤으로 정함
   - 발표 그룹을 지정하고 격주 랜덤 발표
   - 발표자는 당일날 선정
   - 발표 자료는 깃허브 올리는 것으로
   - https://github.com/kotlin-korea
2. 스터디 날짜
   - 매주 일요일 오전
3. 장소는 전주에 확정 지음
   - 히든스페이스
   - 토즈
4. 지디지 코리아 안드로이드가 진행하는 스터디
5. 분량
   - 발표 스타일 자유
   - 책 순서는 기본적으로 지키도록
6. 비용
   - 미리내기 (3만원)  - (통장정보 : 카카오뱅크 3333-01-0818204, 노현석)
   - 매회차 전원 N 빵
   - 벌금 : X 없음
7. 제외대상
   - 몇회 미참석시 Drop은 다 동의
8. 발표 그룹
   - 프루가 랜덤돌림
9. 차주 발표
   - 2~3장 발표

**Comment by hyunji92** [comment]
![2018-02-25-11-17-26](https://user-images.githubusercontent.com/10173050/36637348-adf38706-1a1d-11e8-9b86-bd6d27313d79.jpg)

**Comment by Pluu** [comment]
## 발표 그룹 랜덤 결과
- 1그룹 : [박준선, 김범준, 정현지, 강경완, 권태환, 박준호]
- 2그룹 : [이재호, 양정윤, 도창욱, 이혜정, 노현석, 정진철]

**Comment by hyunji92** [comment]
다음주는 어느그룹 먼저인가용?

**Comment by Pluu** [comment]
@hyunji92  당연히 1 그룹 아닌가요 ㅎ
