### ISSUE TITLE
[Namsadang/Aries] 비용 로그

### ISSUE THREAD

**Issue by Pluu** [kotlin-korea/Study-Log#59]
## 비용 기록

| 요일 | 비용 | 잔액 |
| :--: | :--: | :--: |
| 최초 |   | ₩ 360,000 |
| 3/4 | 스터디룸 : ₩ 60,000 | ₩ 300,000 |
| 3/4 | 음료 : ₩ 14,600 | ₩ 285,400 |
| 3/11 | 스터디룸 : ₩ 80,000 | ₩ 200,400 | 
| 3/18 | 스터디룸 : ₩ 80,000 | ₩ 120,400 | 
| 3/25 | 스터디룸 : ₩ 80,000 | ₩ 40,400 | 
| 2회 입금 | ₩ 360,000 | ₩ 400,400 | 
| 4/1 | 스터디룸 : ₩ 55,000 | ₩ 345,400 |  
| 4/8 | 스터디룸 : ₩ 80,000 | ₩ 265,400 |
| 4/15 | 스터디룸 : ₩ 80,000 | ₩ 185,400 |
| 4/29 | 스터디룸 : ₩ 80,000 | ₩ 105,400 |  
| 5/20 | 점심식사 : ₩ 20,000 | ₩ 85,400 | 
|  | (@Pluu, @omjoonkim, @WickeDev) |  |

## 회비 입금
| 이름 | 1회차 | 2회차 |
| :--: | :--: | :--: |
| 강경완 | O | O |
| 권태환 | O | O |
| 김범준 | O | O |
| 노현석 | O | O |
| 도창욱 | O | O |
| 박준선 | O | O |
| 박준호 | O | O |
| 양정윤 | O | O |
| 이재호 | O | O |
| 이혜정 | O | O |
| 정진철 | O | O |
| 정현지 | O | O |

**Comment by tonyjs** [comment]
입금했어용~~
회비 입금은 @Pluu 님이 확인해야되니 커멘트로 남길께요. 아니면 입금 하고 O 처리 바로 할까요?

**Comment by Pluu** [comment]
@tonyjs 제가 수시로 하고있습니다 ㅋ
