### ISSUE TITLE
Custom getter/setter vs. Property delegation

### ISSUE THREAD

**Issue by cwdoh** [kotlin-korea/Study-Log#62]
언제 써야 하는가에 대한 단상

## Custom getter/setter

* backing field 가 자기 자신 뿐이거나 없다.
* 따라서,
    * 클래스 내에 존재하는 다른 필드와 자신의 backing field 기반의 연산일 경우
    * \+ 재활용할 필요가 없을 경우

## Property delegation

* 재활용이 가능한 경우
* \+ delegation 내에 여러 가용 필드를 자유롭게 정의할 수 있으므로,
    * 여러가지 상태를 관리한다던가.
    * 다른 레퍼런스 등을 저장 처리하는 경우도 이에 해당

---
다른 혹은 추가 의견?

**Comment by cwdoh** [comment]
cost에 대한 고민 추가

**Comment by hixguru** [comment]
여기에 궁금한 내용을 쓰레드로 달아도 괜찮은가요? 성격에 맞지 않는다면 지우겠습니다!
Custom getter에서 `재활용할 필요가 없는 경우`는 해당 값을 캐싱하지 않고 매번 새로운 객체를 생성해서 return해주기 떄문인건가요? 얼마 전에 어떤 포스팅에서 읽은 기억이 있긴한데 정확히 기억이 잘 안 나네요 😓

**Comment by cwdoh** [comment]
아 얼마든지 코멘트하셔도 괜찮습니다.

여기서 재활용은 코드 재활용의 의미였는데요. Observable과 같이 여러 모듈애서 재사용하는 기능이 아니라 특정 클래스에서만 의미를 가지는 한정적인 로직일 경우는 그냥 getter로 구현해도 되겠다라는 의미였습니다. :)

**Comment by cwdoh** [comment]
더불어서 computed prop 형태에서 어떤 객체를 직접 생성하고 이것이 immutable하다면 이 역시 delegation을 사용하는게 맞겠네요. :)
