### ISSUE TITLE
Kotlin in Action 4장

### ISSUE THREAD

**Issue by Pluu** [kotlin-korea/Study-Log#64]
# 4장

## 4.1 클래스 계층 정의

- Kotlin interface 는 자바 8과 비슷
- Default Method 정의가능
  - Java 에서 implements 경우 Default Method 는 재정의 필요
- override modifier 사용
- 복수 interface implement시 동일 함수 존재하는 경우
  - 명시적 override -> super<T>.method() 로 사용
- Kotlin의 Class, Method, Property 는 기본 final -> open 사용으로 override 가능
  - fianl override 로 override 된 이후 막을 수 있음
- 추상 class / method : `abstract` keyword
- internal 키워드 : module 단위 Access Modifier
  - internal 로 정의된 함수는 public 함수에서 호출 불가능

```kotlin
internal open class AA {
    private fun private_yell() = println("private_yell")
    protected fun protected_yell() = println("protected_yell")
}

fun AA.getA() {      // ← internal class는 확장 불가능
    private_yell()   // ← private 접근 불가능 
    protected_yell() // ← protected 접근 불가능
}

// Error:(5, 5) Kotlin: 'public' member exposes its 'internal' receiver type AA
```

> 어떤 클래스의 기반 타입 목록에 들어있는 타입이나 제네릭 클래스의 타입 파라미터에 들어있는 타입의 가시성은 그 클래스의 자신의 가시성과 같거나 더 높아야하고, 메소드의 시그니처에 사용된 모든 타입의 가시성은 그 메소드의 가시성과 같거나 더 높아야 한다는 더 일반적인 규칙에 해당

> Kotlin private class → Java package class
> Kotlin internal → Java public

- 중첩 클래스 외부 참조시 : `inner` Modifier
- `sealed` class : 클래스 계층 확장 제한 (when의 else 사용 제외)

## 4.2 뻔하지 않은 생성자와 프로퍼티를 갖는 클래스 선언

- 생성자로 넘어온 데이터 property의 초기화 처리 가능
- `private constructor` 로 비공개 처리
- interface 내부에 추상 property 정의 가능
  - 주 생성자 : override 
  - Custom Getter
  - Property 초기화
- `뒷받침하는 필드` →  Backing Field
  - custom setter  사용시, this = value 로 할 경우 `StackOverlfowException` 발생

## 4.3 컴파일러가 생성한 메소드: Data Class와 Class Delegation

- `==` : 내부 적 equals, `===`: 참조 비교
- Data class : toString, equals, hashCode, copy 자동 처리
- Class Delegation
  - ★★★ 하나만 가능

```kotlin
interface Base {
    fun print()
}

class BaseImpl(val x: Int) : Base {
    override fun print() { print(x) }
}

class Derived(b: Base) : Base by b

fun main(args: Array<String>) {
    val b = BaseImpl(10)
    Derived(b).print() // prints 10
}
```

> 참고 : [Dependency 101](https://github.com/kotlin-korea/Study-Log/issues/29)

## 4.4 object  키워드

- `object`
  - 싱글턴 정의
  - companion object : Factory 패턴에 유용, 해당 private function 접근 가능
  -  Annonymous inner class
- companion object의 확장 함수

```kotlin
class Person(val firstName: String, val lastName: String) {
    companion object {
    }
}
fun Person.Companion.fromJSON(json: String): Person {
... 
}
val p = Person.fromJSON(json)
```

**Comment by hyunji92** [comment]
LGTM
