### ISSUE TITLE
Kotlin in action 8장

### ISSUE THREAD

**Issue by Pluu** [kotlin-korea/Study-Log#69]
# 8장, 고차 함수 : 파라미터와 반환 값으로 람다 사용

## 8.1 고차 함수 정의

고차함수란, 다른 함수를 인자로 받거나 함수를 반환하는 함수

### 8.1.1 함수 타입

- `(A, B) -> C` : 인자 A, B를 받고 C 를 반환
- `{ x, y -> x + y }` : 타입 추론이 가능할때 인자의 타입을 생략 가능

```kotlin
// 함수 타입의 각 파라미터에 이름 정의 가능
fun performRequest(
       url: String,
       callback: (code: Int, content: String) -> Unit
  ){
/*...*/
}
```

### 8.1.2 인자로 받은 함수 호출

```kotlin
fun A.filter(predicate: (B) -> C) : D

// A         : Receiver type
// predicate : Parameter name
// (B) -> C  : Parameter function type
// B         : Parameter type of function passed as parameter
// C         : Return type of function passed as parameter
```

```kotlin
// predicate Function Type is non-null
fun filter(predicate: (Int) -> Boolean) {
    predicate(1)
}
```

### 8.1.3 자바에서 코틀린 함수 타입 사용

파라매터 22개의 처리를 위한 Functions 미리 구현됨

- [Functions.kt](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/runtime/kotlin/jvm/functions/Functions.kt)
- 코틀린 함수를 자바 8 이상에서 사용시 :  람다
- 코틀린 함수를 자바 8 이전에서 사용시 :  FunctionN  인터페이스를 이용해 무명 클래스 사용

### 8.1.4 디폴트 값을 지정한 함수 타입 파라미터나 널이 될 수 있는 함수 타입 파라미터

```kotlin
fun <T> Collection<T>.joinToString(
        separator: String = ", ",
        prefix: String = "",
        postfix: String = "",
        transform: (T) -> String = { it.toString() }
): String { }
```

```kotlin
// predicate Function Type is nullable
fun filter2(predicate: ((Int) -> Boolean)?) {
    predicate?.invoke(1)
    predicate?.let { it(1) }
}
```

### 8.1.5 함수를 함수에서 반환

```kotlin
fun fuction() : (A) -> B { }
// A 파라미터를 받고, B 가 반환되는 함수를 반환
```

- 함수 반환 방법 : return 식에 람다나 식을 이용

> return { order -> 1.2 * order.itemCount }

### 8.2.1 인라이닝이 작동하는 방식

`inline` : 함수의 본문이 인라인 된다. 함수를 호출하는 코드를 함수를 호출하는 바이트코드 대신 함수 본문을 번역한 바이트코드로 컴파일한다

- 기본적으로 inline 함수의 파라미터로 정의된 람다의 본문도 함께 인라인
- 람다 대신 함수 타입의 변수를 전달하는 경우 인라인되지않음

### 8.2.2 인라인 함수의 한계

` noinline`: 인라이닝하면 안되는 람다를 파라미터로 받을 경우 인라이닝 금지 처리 가능

### 8.2.4 함수를 인라인으로 선언해야 하는 경우

- inline 키워드를 사용해도 람다를 인자로 받는 함수의 경우가 이익이 더 많다
  1. 함수 호출 비용을 낮춤
     1. 람다를 표현하는 클래스, 람다 인스턴스에 해당하는 객체 생성이 불필요
  2. 현재 JVM은 함수 호출과 람다를 인라이닝 불가능
  3. 일반 람다로는 사용 불가능한 기능 사용 가능 (non-local 등)

```kotlin
@InlineOnly
@RequireKotlin("1.2", versionKind = RequireKotlinVersionKind.COMPILER_VERSION, message = "Requires newer compiler version to be inlined correctly.")
public inline fun <T : Closeable?, R> T.use(block: (T) -> R): R {
    var exception: Throwable? = null
    try {
        return block(this)
    } catch (e: Throwable) {
        exception = e
        throw e
    } finally {
        when {
            apiVersionIsAtLeast(1, 1, 0) -> this.closeFinally(exception)
            this == null -> {}
            exception == null -> close()
            else ->
                try {
                    close()
                } catch (closeException: Throwable) {
                    // cause.addSuppressed(closeException) // ignored here
                }
        }
    }
}
```

### 8.3.1 람다 안의 return문 : 람다를 둘러싼 함수로부터 반환

람다 안에서 return 을 사용하면 람다로부터만 반환되는 게 아니라 그 람다를 호출하는 함수가 실행을 끝내고 반환

```kotlin
fun lookForAlice(people: List<Person>) {
    people.forEach {
        if (it.name == "Alice") {
            println("Found!")
            return
} }
    println("Alice is not found")
}
```

- Non-local return : 자신을 둘러싸고 있는 블록보다 더 바깥에 있는 다른 블록을 반환하게 만드는 return문 
- return 코드의 Code Completion 시 아래의 코드가 알림
  - return
  - return@forEach

### 8.3.2 람다로부터 반환: 레이블을 사용한 return

로컬 return과 넌로컬 return 구분 : `label` 사용

### 8.3.3 무명 함수(Anonymous functions): 기본적으로 로컬 return

```kotlin
// 람다 대신 무명함수 사용
// 해당 return 은 가장 가까운 함수를 가리킴
fun lookForAlice(people: List<Person>) {
    people.forEach(fun (person) {
        if (person.name == "Alice") return
        println("${person.name} is not Alice")
    })
}

// val people = listOf(Person("Alice", 29), Person("Bob", 31))
// >> lookForAlice(people)
// Bob is not Alice
```

![return / fun](https://dpzbhybb2pdcj.cloudfront.net/jemerov/Figures/08fig05.jpg)

**Comment by cwdoh** [comment]
## 인라인 관련 keyword note

### inline

호출부에 함수의 구현부를 inlining한다. 코드 수준에서 삽입이 일어나므로 local-control-flow가 가능

### noinline

전달받은 함수를 lambda 등으로 재전달해야 할 경우, 이를 inlining하지 않기 위해 `noinline`으로 함수 객체를 유지한다.

### crossinline

기본적으로 전달된 lambda를 구현 함수의 요건(inline 등)에 맞추어 적용하지만, local-control-flow는 허가하지 않는다. local-control-flow에 의해 구현 함수가 예기치 않은 반환 등으로 종료되는 것을 막기 위함이다.
* 간단하게 보면 framework 등에서 제공하는 method가 성능 이슈 등으로 `inline`되기를 원하나, 해당 함수가 외부로부터 전달받은 람다 등에 의해 기본적인 동작 흐름이 깨지는 것을 막기 위함이다.
